name: Deploy Automático a GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Subir cambios por SFTP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Sincronizar Código Fuente (test_migration)
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        local_dir: .
        server-dir: test_migration/